title: LVAD Caregiver Study
author: Ashley Xu, PhD
email: ashleyxu@jhu.edu
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

sass:
    style: compressed